#springboot日志格式
logging:
  pattern:
    console: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %line %clr(:){faint} %m%n'

spring:
  datasource:
    url: 'jdbc:mysql://localhost/inst02'
    username: root
    password: '@gnnaa1993'
    driver-class-name: com.mysql.cj.jdbc.Driver